---
deployment:
      tasks:
        - export DEPLOYPATH=/home/oriorrzc/public_html
        - echo "Starting deployment" >> deployment.log
        - /bin/cp -R public/* $DEPLOYPATH
        - echo "Deployment public completed" >> deployment.log